# .streamlit/secrets.toml

[creds]
type = "service_account"
project_id = "sistemagcm"
private_key_id = "1b92a4b17d8d737ef8519991f1c3c0d7916e3815"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC50MBGGHOO+FoL
2qJEF3u/RCwUaaD8fEgq/oHWZB9Yiv/olDr2MyIyfDwXWLR78Aze+RfgF/2uIk/h
fyWYasbaelAa2266aU4W0EbcH3P2yCp1exqVljUAcjl5BoY+0xHOMREKaOaZD0+v
KgwD/WBpc71aOL8EqjUTg+FVajZh+ECwg1GJnLpI345kErmIV9AevaJ6v9lt4zlo
35ojfgelDVEVpSFyXb/5l+Sz3HZPwfSB1QjMbjkG7Qbi5IzbGDpNxZ6PMj9rHnOH
SWYE/pYX+qzGjF6MUHfCogVZMiwL+oS/zek8nlI2ChiI0kfEzRaelMtw+xAWFvOX
EuXdUlUbAgMBAAECggEANHSW4vLiJHk9ylzlM/3BJGSVYQnUtZJMOT7x3lkTdEaB
KeI2puwWelQSDrEu+lHxAD0nnU6IgdET5d+j+FwkWObwmDRcFOnHbq9LYbbLYN5v
Bg1Dmvj1a3PTf7P0z+V8AE5ftiWY+5qT7yoajEHKJtrSmJaubh2ysBip0xgR1CPq
0Uh/PoRpzrtz2bddcui59P9K6FYICq9E+BsyAVwx3sC2aez0BbPgfCJLVxZ6Z0P+
qtROpa3xhbjxWRVVEMtQ6fIVlUJIbRUwI8Jtp59BicqeQ8hKZZcgJAFFrc+Qks8K
j2gHUNownDCGK90nHONSlJ9a80GsL2r1WyFJHDV1iQKBgQDcQ3N+NzlzfCGtOsxM
PGdJ1Ov3UCpPhuI7X6rUfLmyN/c8rxSykub55Q2n0EvEYW94lFXDtSBN09RpMuVr
QmISlD2ADGEG8IhaJM1sz+xRAaHvL3JOm0CF+HeRST+W2VMB3DdIjVpTHxxc4FUj
jel7vdmpL6gNSPat8+UBJGLF3QKBgQDX9oPero+3gDgRGrq2KLGtqKCW+7DqxBMj
NgWu044IpROu/l2m1bla8ILiQC3rSgrygAvOfldMKSQO6oEWTcAw7DsYOWZHMkr5
eiNJK9DKYRs0zhi3tETKxG57Gq6KX0GxYB0yfNmf1Gz83fNr1anl2RR400wEYKCg
xGvBePWDVwKBgHucUvVTMqev0wpvg/WItIKHvoEFeSk2TkH511n2QRRWOibRLrFk
pcE6HWa/C7ZC5BbsUBFL1bw3k+4RxRRjpbw9eyIgUFdfp3XHT42wRjPT0bf0jZa1
pAlLPnbHf6s9fUr+9ft+cGFThUxODRmt64kpKzy6ZPpHp0BKLotsiw31AoGAIlBT
4ZTg1uozflw94GWU3Z/WbEbvdE3VMJoLyxxoC+2WtA5MeQ6qVc2zLhm+cg0gsikw
Nw4R9tLunMQb4JxX9i4CsbWlD5jpGrySULT6hr1pIjnA6adl6sXNPBggNXIvMOyx
lu0JcwDAlGj7nV2kkhWs0AnaoTNtMj4jVOlQMR8CgYEAgFJxelp/55mAYZpE0VP/
c7HAB7yDDJemNjVA6krBsoKv9N5ecWk69lQb6EvC/LZgdfPYL+8K8BW9gDX2sZN4
vKEOxNcRf8MiAIM9H1wxCDB1oC3QxtQVXk0AhMCfZQi8nr51ez1BH44axVlvuB10
WW5ElcDp3J0FAjjhulQ5AMk=
-----END PRIVATE KEY-----"""
client_email = "bot-gcm@sistemagcm.iam.gserviceaccount.com"
client_id = "101789689057850471067"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/bot-gcm%40sistemagcm.iam.gserviceaccount.com"

# Aqui fora da seção [creds], definimos sheet_id:
sheet_id = "1K8YAEd9bSBS4W-fMgWQ_uMPfHJF22UFpSe-Ihv5CSnM"
