# .streamlit/secrets.toml

[creds]
type = "service_account"
project_id = "sistemagcm"
private_key_id = "1b92a4b17d8d737ef8519991f1c3c0d7916e3815"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC50MBGGHOO+FoL
… (toda sua chave PEM aqui, sem barras extras nem \\n) …
-----END PRIVATE KEY-----"""
client_email = "bot-gcm@sistemagcm.iam.gserviceaccount.com"
client_id = "101789689057850471067"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/bot-gcm%40sistemagcm.iam.gserviceaccount.com"

sheet_id = "1K8YAEd9bSBS4W-fMgWQ_uMPfHJF22UFpSe-Ihv5CSnM"
